export enum userActions {
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  REGISTER_FAIL = "REGISTER_FAIL",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_FAIL = "LOGIN_FAIL",
  LOGOUT = "LOGOUT",
  RESET_SUCCESS = "RESET_SUCCESS",
  RESET_FAIL = "RESET_FAIL",
}

export const TOKEN = "Token"